### ISSUE TITLE
proposal: web app 

### ISSUE THREAD

**Issue by biwek** [bishesh/Science-innovation-Nepal#11]
As discussed with @bishesh:

**Problem**
There lies an existing issue where users have to register on github or pass info of innovators to be added to the site. This may not sound that critical but I think it does impact on the growth of this site.

**Plan:**
Although there are few _other_ ways of overcoming the above problem, my proposal was to create a web app which accepts user inputs and stores it in the app's db, instead of the existing static site.
I believe this would benefit the site with better data collection, easier filtering, categorisation and so on moving forward.

Thoughts?

**Comment by bishesh** [comment]
That's a very good idea @biwek . Thanks for the initiation on that.
1. I am not familiar with database management systems (DBMS) and the development of dynamic website. Thus, someone else has to take lead on that; would be great if you can take the lead :)
2. For the development of the (new) website and DBMS, can you estimate the needed man-hours with the expertise you have ? Please be aware that you might be all alone in the beginning days of getting the prototype ready. If you are fine with that, that's great!
Later on, we will need to find ways to attract other volunteers with the expertise to help develop the system. I have already seen few people using the website to find Nepali scholars in their field of interest, so it might not be that difficult to get more volunteers in the long run.   
3. We will need a server to store the database and a hosting website. I am ready to contribute the cost for the first years, but we will need a more sustainable way (donations like wikipedia ?). Also estimates of the annual cost ?
4. The website source code and the data both are open source right now, with apparently no security issues due to the static nature of the website which is hosted in github pages. I think we will have to keep the data open in the future too. I am inclined to keep the source code open source too, but I remember you saying that this can make the website less secure. As for now, I am fine with closed source code too.

I'm happy if you can take the lead and let us know the next steps.

**Comment by biwek** [comment]
Happy to take lead on this @bishesh.

In terms of time it will take, I'm not really sure. I'll be working on it during my free hours, however, the initial implementation should be quite simple.

In terms of cost, things I can think of is getting a domain and hosting the app. There are few options here which we can look at later stage. However it would be good to get the domain name sooner if you had one in mind.

I can start off the project on a private repo. Later as discussed, I'm happy for it to be open if we can get the community involved on it too.

I'll try to start work on it soon. I'll be in touch wrt the progress or if I have any questions.

**Comment by bishesh** [comment]
Sounds good.

For the domain name, I have sent you a private email. Once we have a domain, I can link our existing website to the new domain name. 

For the private repo, can we use gitlab ? Please add me on that repo so that we can discuss about any issues regarding the development of the new website over there. Once the new website is ready, we can replace the existing one with it.

**Comment by bishesh** [comment]
Hi @biwek , Any updates on this ?

**Comment by biwek** [comment]
Apologies @bishesh. Haven't been able to spend much time on it yet. Hopefully will be able to share a prototype by the end of the month.

**Comment by biwek** [comment]
Closing as the app is now [live](https://abhinavnepal.com). A separate [repo](https://github.com/AbhinavNepal/abhinav-nepal) has been created.
